export const VENDOR_CONSENT_COOKIE_NAME = 'euconsent'
export const VENDOR_CONSENT_COOKIE_MAX_AGE = 33696000
export const VENDOR_CONSENT_COOKIE_DEFAULT_PATH = '/'
export const VENDOR_CONSENT_COOKIE_SAME_SITE_LOCAL_VALUE = 'lax'
export const VENDOR_CONSENT_COOKIE_SAME_SITE_GLOBAL_VALUE = 'none'
export const VENDOR_CONSENT_COOKIE_SECURE_GLOBAL_VALUE = 'Secure'
