import {LEVEL} from '../service/log/Log'
import {OPTION_USE_SAME_THAN_ALL_CUSTOM_IS_TRUE} from '../../domain/vendor_consents/NewVendorsStatusService'

const DEFAULT_CONSENT_SCREEN = 1
const DEFAULT_CONSENT_LANGUAGE = 'es'
const DEFAULT_LOG_LEVEL = LEVEL.warn
const DEFAULT_GDPR_APPLIES = true
const DEFAULT_GDPR_STORE_CONSENT_GLOBALLY = false
const DEFAULT_VENDOR_LIST_HOST = 'https://c.dcdn.es/cmp/vendorlist'
const DEFAULT_VENDOR_LIST_FILENAME = 'vendorlist.json'
const DEFAULT_DEBUG_KEYWORD = 'cmp_debug'
const DEFAULT_NEW_VENDORS_STATUS_OPTION = OPTION_USE_SAME_THAN_ALL_CUSTOM_IS_TRUE

export {
  DEFAULT_CONSENT_SCREEN,
  DEFAULT_CONSENT_LANGUAGE,
  DEFAULT_LOG_LEVEL,
  DEFAULT_GDPR_APPLIES,
  DEFAULT_GDPR_STORE_CONSENT_GLOBALLY,
  DEFAULT_VENDOR_LIST_HOST,
  DEFAULT_VENDOR_LIST_FILENAME,
  DEFAULT_DEBUG_KEYWORD,
  DEFAULT_NEW_VENDORS_STATUS_OPTION
}
