import {
  latestVendorListLocator,
  versionVendorListLocator
} from '../../domain/vendor_list/iabVendorListLocator'
import {LEVEL} from '../service/log/Log'

const DEFAULT_CONSENT_SCREEN = 1
const DEFAULT_CONSENT_LANGUAGE = 'en'
const DEFAULT_LOG_LEVEL = LEVEL.warn
const DEFAULT_GDPR_APPLIES = true
const DEFAULT_GDPR_STORE_CONSENT_GLOBALLY = false
const DEFAULT_VENDOR_LIST_LATEST_LOCATOR = latestVendorListLocator
const DEFAULT_VENDOR_LIST_VERSION_LOCATOR = versionVendorListLocator
const DEFAULT_DEBUG_KEYWORD = 'cmp_debug'

export {
  DEFAULT_CONSENT_SCREEN,
  DEFAULT_CONSENT_LANGUAGE,
  DEFAULT_LOG_LEVEL,
  DEFAULT_GDPR_APPLIES,
  DEFAULT_GDPR_STORE_CONSENT_GLOBALLY,
  DEFAULT_VENDOR_LIST_LATEST_LOCATOR,
  DEFAULT_VENDOR_LIST_VERSION_LOCATOR,
  DEFAULT_DEBUG_KEYWORD
}
