import {LEVEL} from '../Log'

const DEFAULT_CONSENT_SCREEN = 1
const DEFAULT_CONSENT_LANGUAGE = 'es'
const DEFAULT_LOG_LEVEL = LEVEL.warn
const DEFAULT_GDPR_APPLIES = true
const DEFAULT_GDPR_STORE_CONSENT_GLOBALLY = false
const DEFAULT_VENDOR_LIST_HOST = 'https://vendorlist.consensu.org'
const DEFAULT_VENDOR_LIST_FILENAME = 'vendorlist.json'
const DEFAULT_DEBUG_KEYWORD = 'cmp_debug'

export {
  DEFAULT_CONSENT_SCREEN,
  DEFAULT_CONSENT_LANGUAGE,
  DEFAULT_LOG_LEVEL,
  DEFAULT_GDPR_APPLIES,
  DEFAULT_GDPR_STORE_CONSENT_GLOBALLY,
  DEFAULT_VENDOR_LIST_HOST,
  DEFAULT_VENDOR_LIST_FILENAME,
  DEFAULT_DEBUG_KEYWORD
}
